---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ./crypto-config/ordererOrganizations/etsiit.ugr/msp

    - &atc
        Name: atcMSP
        ID: atcMSP
        MSPDir: ./crypto-config/peerOrganizations/atc.etsiit.ugr/msp

    - &decsai
        Name: decsaiMSP
        ID: decsaiMSP
        MSPDir: ./crypto-config/peerOrganizations/decsai.etsiit.ugr/msp

    - &lsi
        Name: lsiMSP
        ID: lsiMSP
        MSPDir: ./crypto-config/peerOrganizations/lsi.etsiit.ugr/msp
  
    - &tstc
        Name: tstcMSP
        ID: tstcMSP
        MSPDir: ./crypto-config/peerOrganizations/tstc.etsiit.ugr/msp

Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses:
        - orderer.etsiit.ugr:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:

    ThreeOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *atc
                    - *decsai
                    - *lsi
                    - *tstc
    ChannelAll:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *atc
                - *decsai
                - *lsi
                - *tstc