version: '2'

networks:
    fabric:

services:
    peer0.lsi.etsiit.ugr:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.lsi.etsiit.ugr
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.lsi.etsiit.ugr:7052
            - CORE_PEER_ID=peer0.lsi.etsiit.ugr
            - CORE_PEER_ADDRESS=peer0.lsi.etsiit.ugr:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.atc.etsiit.ugr:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=lsiMSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@lsi.etsiit.ugr/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@lsi.etsiit.ugr/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@lsi.etsiit.ugr/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/lsi.etsiit.ugr/peers/peer0.lsi.etsiit.ugr/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/lsi.etsiit.ugr/peers/peer0.lsi.etsiit.ugr/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/lsi.etsiit.ugr/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
        extra_hosts:
            - "orderer.etsiit.ugr:192.168.56.220"
            - "peer0.atc.etsiit.ugr:192.168.56.221"
            - "peer0.decsai.etsiit.ugr:192.168.56.222"
            - "peer0.tstc.etsiit.ugr:192.168.56.224"
        networks:
          fabric:
             aliases:
               - net
        ports:
          - 7051:7051
          - 7053:7053

    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.lsi.etsiit.ugr:7051
          - CORE_PEER_LOCALMSPID=lsiMSP
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/lsi.etsiit.ugr/users/Admin@lsi.etsiit.ugr/msp
          - CORE_CHAINCODE_KEEPALIVE=10
        extra_hosts:
          - "orderer.etsiit.ugr:172.31.60.217"
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../../chaincode/:/opt/gopath/src/github.com/chaincode
            - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
          - peer0.lsi.etsiit.ugr
        networks:
            - fabric